version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    ports:
      - "3306:3306"
    platform: linux/x86_64
    volumes:
      - ./mysql:/var/lib/mysql

  
